---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur-garage
  namespace: kopiur-system
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
      tolerations:
        - key: machine-cold
          operator: Exists
          effect: NoSchedule
    controllers:
      main:
        # initContainers:
        #   startup:
        #     enabled: true
        #     image:
        #       repository: busybox
        #       tag: "1.38.0"
        #     command: chown
        #     args:
        #       - -R
        #       - 1000:100
        #       - /data
        containers:
          main:
            image:
              repository: dxflrs/garage
              tag: v2.3.0
            command: "/garage"
            args:
              - server
              - --single-node
              - --default-bucket
            env:
              TZ: "America/Chicago"
            envFrom:
              - secretRef:
                  name: kopiur-garage-secrets
    service:
      main:
        controller: main
        ports:
          s3:
            port: 3900
          api:
            port: 3903
      lb:
        annotations:
          metallb.io/loadBalancerIPs: 10.10.201.8
        type: LoadBalancer
        controller: main
        ports:
          s3:
            port: 3900
    configMaps:
      config:
        enabled: true
        data:
          configuration.toml: |
            metadata_dir = "/meta"
            data_dir = "/data"
            db_engine = "lmdb"
            metadata_auto_snapshot_interval = "6h"

            replication_factor = 1
            compression_level = 2

            rpc_bind_addr = "[::]:3901"
            rpc_public_addr = "127.0.0.1:3901"

            [s3_api]
            s3_region = "us-east-1"
            api_bind_addr = "[::]:3900"
            root_domain = ".s3.iwrite.software"

            [admin]
            api_bind_addr = "[::]:3903"
    persistence:
      config:
        enabled: true
        type: configMap
        name: kopiur-garage
        globalMounts:
          - path: /etc/garage.toml
            subPath: configuration.toml
      data:
        enabled: true
        globalMounts:
          - path: /data
        type: persistentVolumeClaim
        existingClaim: local-kopiur-data-pvc
      meta:
        enabled: true
        globalMounts:
          - path: /meta
        type: persistentVolumeClaim
        existingClaim: local-kopiur-meta-pvc
