---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      main:
        type: statefulset
        replicas: 2
        containers:
          main:
            image:
              repository: quay.io/keycloak/keycloak
              tag: 26.7.2
            args:
              - start
            env:
              TZ: "America/Chicago"
              KC_BOOTSTRAP_ADMIN_USERNAME: admin
              KC_BOOTSTRAP_ADMIN_PASSWORD: admin
              KC_HOSTNAME_STRICT: "true"
              KC_HEALTH_ENABLED: "true"
              KC_CACHE: "ispn"
              POD_IP:
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              KC_CACHE_EMBEDDED_NETWORK_BIND_ADDRESS: "$(POD_IP)"
              KC_DB: postgres
              KC_DB_URL_DATABASE: app
              KC_DB_URL_HOST: keycloak-postgres-cluster-rw.tools.svc.cluster.local
              KC_DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: keycloak-postgres-cluster-superuser
                    key: password
              KC_DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: keycloak-postgres-cluster-superuser
                    key: username
            # probes:
            #   startup:
            #     httpGet:
            #       path: /health/started
            #       port: 9000
            #     periodSeconds: 1
            #     failureThreshold: 600
            #   readiness:
            #     httpGet:
            #       path: /health/ready
            #       port: 9000
            #     periodSeconds: 10
            #     failureThreshold: 3
            #   liveness:
            #     httpGet:
            #       path: /health/live
            #       port: 9000
            #     periodSeconds: 10
            #     failureThreshold: 3
            resources:
              limits:
                cpu: 2000m
                memory: 2000Mi
              requests:
                cpu: 500m
                memory: 1700Mi

    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
          jgroups:
            enabled: true
            protocol: TCP
            port: 7800
          jgroups-fd:
            enabled: true
            protocol: TCP
            port: 57800
    ingress:
      main:
        enabled: false
        className: "cloudflare-tunnel"
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host auth.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: acme-crt-secret-sparks-codes
      internal:
        enabled: true
        className: traefik
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/info: "Keycloak"
          hajimari.io/icon: "key-chain"
          hajimari.io/targetBlank: "true"
        hosts:
          - host: *host
            paths:
              - path: "/"
                pathType: "Prefix"
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: acme-crt-secret-sparks-codes
