apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:FGXQlthtlHBoNWZg3zzCvJqLLceDWiNI2eJ+E8UI6Dv9oU9J8Du32y6cZKU=,iv:4ChqFO5zFHY0+dTCWK4wCIeAL/ZvMgzvG9ktR4t5Psg=,tag:stHROydYdy7BbOeZz/XgyA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: zigbee2mqtt-secret
    namespace: home
sops:
    age:
        - enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbTFpMUlzQVhPREVETUg2
              M2N2Mlc3Ny9QM083WFo3aCtZeGpFZTlkQ3lZCks5Z2EvaTdZdW41WHdndUYxY2VH
              WFhOUTBRdlRheXNJc1BJSEZuS2ZwR1EKLS0tIFZmUkJaK3pjd1d0eFVWVTNPaDU3
              OGNNdmQwRElZaHpNZGY1cjVnZ2huUG8KRwtobvOAZbyiJ8RrkFhvZ08LYdI2wQFi
              tuP1AUzRgGSRuKcJJzqhYQGGRAfPmjGXqf21prUQ1LIj0+9Xi+G8Jg==
              -----END AGE ENCRYPTED FILE-----
          recipient: age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T20:06:55Z"
    mac: ENC[AES256_GCM,data:dhy5eAML7n98SIRUwHnVVTud+9f4346t2EPvJdpmcssr7qmkTIIT5Y1l9pciirm2QoQYAFIe1G78MI+tf592b9YO7M86OXEaE+3EnIwblR5aLxymixj25DM7RkvTcdWpvti21q8sblRX9slHnFpzn5oFw1y0L6plFeD6qiMokB8=,iv:K0TDtKc40sCBv+ccUnf/sSrxgkhrqWuhGH32GP/uZls=,tag:9QBW3pC0kjeLwf3YHzn70w==,type:str]
    version: 3.13.1
