apiVersion: v1
stringData:
    auth: ENC[AES256_GCM,data:FRd4xugWZQOdM0OSi/96ZsLJC0TJ6wmATjBiyFzqNkap/5AvCIVusxdPHHE=,iv:R2xLMA/CKp1M/by8ebqAqaphYQx++kNtLOxXC2pmbYM=,tag:XyH3Urp/u6Ir/RMVr5IxrQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: zigbee2mqtt-secret
    namespace: home
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbTFpMUlzQVhPREVETUg2
            M2N2Mlc3Ny9QM083WFo3aCtZeGpFZTlkQ3lZCks5Z2EvaTdZdW41WHdndUYxY2VH
            WFhOUTBRdlRheXNJc1BJSEZuS2ZwR1EKLS0tIFZmUkJaK3pjd1d0eFVWVTNPaDU3
            OGNNdmQwRElZaHpNZGY1cjVnZ2huUG8KRwtobvOAZbyiJ8RrkFhvZ08LYdI2wQFi
            tuP1AUzRgGSRuKcJJzqhYQGGRAfPmjGXqf21prUQ1LIj0+9Xi+G8Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T17:08:17Z"
    mac: ENC[AES256_GCM,data:VSMjLQ8L8/xO5UKQvdLNyuceKDgzuMoeVRxC05ZKxlthdfbXAh0ufx+AcR9EuW3L9QWigtmPIW5Nz3WxNJDazl76T8HLRpa7UdRAIRgx+fIkvhD7PtsZMC5j/FTq+Ut26k2iBfemwfnlLnfx2v+dsMKo5+q9qS4Pvw9XySr5Hkc=,iv:Kuq067Ea/TBilh1aMRIc/4OxTTuBoecygN6KbZx87As=,tag:+uD3YQqWiEhHh2IslPLrAQ==,type:str]
    version: 3.13.1
