apiVersion: v1
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:hJOH83WonZ3soxPPELY6vA==,iv:cIMD5qJm7EXcpELuhS5gwboTABiOkTAktPXduiDUbWo=,tag:coI/wOsF/aX8oWoBGUpU3w==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:x1N7D7XMjXsNM04HBFOdXQ==,iv:WzAvgHBsx4KkUs0kVzJsiixUYqhPqVGhjAxKBNg2Lk8=,tag:3WSA/vtg2ZxRT5tDaUn7nQ==,type:str]
    RUSTFS_CREDENTIALS: ENC[AES256_GCM,data:5cNH8pXyU+jIDd/RIBCZisyIHX9DptAVf0Y4aXGH66dyDTOhn0Y2lEoUuVCjnJ89KjhqhfHgeRQTm1n3sYKct6qBaDppUvbaaMKTQbfjKWPQGmtmMLLDYRC2ObnE7vjAm4a0aEeciyqxATkHkZA8kcwIFijdOyrh9H0Wb19xFhK5feKql05z3ms+Nph8pVxZAp8tescxKWiNJQoJKOmqlSq0wHA9oTbKdxNRkcMxezO8ogZGH1D03HSUYInuZ5+OV6htoOBErQXASw==,iv:OA7ZlsbtkI/Iw1g+naNbFBGf2QNuvy/wT2eiR9WrC2U=,tag:20hYAtw3Fu0/P9lmf8Rd1A==,type:str]
kind: Secret
metadata:
    name: gitlab-secrets
    namespace: gitlab
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUzFKMEFGR3oyOGR0Ni9S
            d0hid2Y3aFNkRlhUa1g5L0RuS0FGdjhGZmx3Ck9MV3lNUG1pUzJoL3E4VGNWZCtq
            d2JJTWhYOHNTN2RqbXZScFBvRTNXRVkKLS0tIEluMXJmZ3h0cmVoWUMwT2Q3Ym8w
            NlFzQXdwbTVkdzlqYWV1MXBZSmRqdWcKKyueXsHUP32fhtXBGuFB/buLRCMPPYOO
            epnhbfo7p1DeE6Dnfli3SG5H2IK7heR6n8LJvaaQ+t8s1lXxVNs6cA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T21:32:24Z"
    mac: ENC[AES256_GCM,data:aG783luI18efXYybpNQLC90iPRvcXvwKNtE6NpTXoHN5ZusiD/SD9TMwIwk63SQk+rdREcAYZ7Dtczs/dI42bdiXhJAyE8mBcYbpFlOS1rFuEN4xOe1FF5MSAAlwcTppARQCjJ2m1rLwaKZ4czwE5L4u4pG0W/4E9YXe3zmJvCs=,iv:tD7RjVhvqLkW7OpIuGJyr0zt81kiQqBgaEeymswXVcA=,tag:ZFnRgqf7q4zL8nkcASJXjQ==,type:str]
    version: 3.13.0
