apiVersion: v1
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:hJOH83WonZ3soxPPELY6vA==,iv:cIMD5qJm7EXcpELuhS5gwboTABiOkTAktPXduiDUbWo=,tag:coI/wOsF/aX8oWoBGUpU3w==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:x1N7D7XMjXsNM04HBFOdXQ==,iv:WzAvgHBsx4KkUs0kVzJsiixUYqhPqVGhjAxKBNg2Lk8=,tag:3WSA/vtg2ZxRT5tDaUn7nQ==,type:str]
    RUSTFS_CREDENTIALS: ENC[AES256_GCM,data:5cNH8pXyU+jIDd/RIBCZisyIHX9DptAVf0Y4aXGH66dyDTOhn0Y2lEoUuVCjnJ89KjhqhfHgeRQTm1n3sYKct6qBaDppUvbaaMKTQbfjKWPQGmtmMLLDYRC2ObnE7vjAm4a0aEeciyqxATkHkZA8kcwIFijdOyrh9H0Wb19xFhK5feKql05z3ms+Nph8pVxZAp8tescxKWiNJQoJKOmqlSq0wHA9oTbKdxNRkcMxezO8ogZGH1D03HSUYInuZ5+OV6htoOBErQXASw==,iv:OA7ZlsbtkI/Iw1g+naNbFBGf2QNuvy/wT2eiR9WrC2U=,tag:20hYAtw3Fu0/P9lmf8Rd1A==,type:str]
    username: ENC[AES256_GCM,data:7c4Fv8/Z,iv:eJZZU79XIUNPYJFmMU3VlGAD3xJ26KrvLZQ5O0VIWW8=,tag:YA3MAwZ40Kz8WPKJoAfCXw==,type:str]
    password: ENC[AES256_GCM,data:bQIN3vbJJN3TmxxrqYSDVS90,iv:yg2+nuCFfgfG0VSkk6LIL7f7K9GrnqgEGwsOaDZCJyM=,tag:IA7rkgKW8ylIcS/jXexjqg==,type:str]
kind: Secret
metadata:
    name: gitlab-secrets
    namespace: gitlab
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUzFKMEFGR3oyOGR0Ni9S
            d0hid2Y3aFNkRlhUa1g5L0RuS0FGdjhGZmx3Ck9MV3lNUG1pUzJoL3E4VGNWZCtq
            d2JJTWhYOHNTN2RqbXZScFBvRTNXRVkKLS0tIEluMXJmZ3h0cmVoWUMwT2Q3Ym8w
            NlFzQXdwbTVkdzlqYWV1MXBZSmRqdWcKKyueXsHUP32fhtXBGuFB/buLRCMPPYOO
            epnhbfo7p1DeE6Dnfli3SG5H2IK7heR6n8LJvaaQ+t8s1lXxVNs6cA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T15:54:06Z"
    mac: ENC[AES256_GCM,data:U6HzssiBURyHmPqlRx5e982TwDGan9LjEJkcbY++Yz1gGFRkf8cojOcAjFRSOry/utFEMQFbxWqicsFxU9oBMFukCVHWaNcBtKyB4ef88uz+Ag+VX3UKcXsn9pREC7VxUgdlbcxEmkcKC1pC0TcPIO0tsxYLpFoWbO3KQyBn7fE=,iv:3LG2mWmk404ROja4pgegx3jxotPjs2iCYSdUQyPNrd4=,tag:sMhdc4x2EIpJzqJU/aLfXw==,type:str]
    version: 3.13.0
