apiVersion: v1
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:hJOH83WonZ3soxPPELY6vA==,iv:cIMD5qJm7EXcpELuhS5gwboTABiOkTAktPXduiDUbWo=,tag:coI/wOsF/aX8oWoBGUpU3w==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:x1N7D7XMjXsNM04HBFOdXQ==,iv:WzAvgHBsx4KkUs0kVzJsiixUYqhPqVGhjAxKBNg2Lk8=,tag:3WSA/vtg2ZxRT5tDaUn7nQ==,type:str]
    RUSTFS_CREDENTIALS: ENC[AES256_GCM,data:2VA7rAaRk8eQSg1groSNf1E/9+aDHgwxWHMr1h55CFJ1PPakxwSSRbVs1JCNNHBple0CkSuUibHzH2Dgp6RWpWRgNmWgzDLor7LbC3vmg5i9T764VF30B3qIGsOlvnG1/xVki814pnMKrCjSZG/7MpaEA2+9C9PSF+Ex8rR5zY78loBgNEQLj54h1eEOcPiG5viardkijRq6QfzOii2RoXh1u8Def5k4p3q2lF/OiSPQQo5CUxqDAT3aweqoolCdvfiIr6VPJDIa9o/1NsB38cn0CbuTqLi0dMtyVsXo9Tg1F5EUc82k,iv:1b5cnUVoILmiUdKdFsmSpJaLC1IHJziGI3cb2N+Mj84=,tag:YNmIzAnOhBbIrrTd+5YlkA==,type:str]
    username: ENC[AES256_GCM,data:7c4Fv8/Z,iv:eJZZU79XIUNPYJFmMU3VlGAD3xJ26KrvLZQ5O0VIWW8=,tag:YA3MAwZ40Kz8WPKJoAfCXw==,type:str]
    password: ENC[AES256_GCM,data:bQIN3vbJJN3TmxxrqYSDVS90,iv:yg2+nuCFfgfG0VSkk6LIL7f7K9GrnqgEGwsOaDZCJyM=,tag:IA7rkgKW8ylIcS/jXexjqg==,type:str]
kind: Secret
metadata:
    name: gitlab-secrets
    namespace: gitlab
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUzFKMEFGR3oyOGR0Ni9S
            d0hid2Y3aFNkRlhUa1g5L0RuS0FGdjhGZmx3Ck9MV3lNUG1pUzJoL3E4VGNWZCtq
            d2JJTWhYOHNTN2RqbXZScFBvRTNXRVkKLS0tIEluMXJmZ3h0cmVoWUMwT2Q3Ym8w
            NlFzQXdwbTVkdzlqYWV1MXBZSmRqdWcKKyueXsHUP32fhtXBGuFB/buLRCMPPYOO
            epnhbfo7p1DeE6Dnfli3SG5H2IK7heR6n8LJvaaQ+t8s1lXxVNs6cA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T16:43:06Z"
    mac: ENC[AES256_GCM,data:ZRAlwz+cw8svqg2Zn7VLq6Tw3067LAIInz6vbknsiayzzCcs/b5AytR7GFtniqgAi9ZJ/YCOuSWYY/H4I3ywFS759vQlC3GySqzLeWlvFCaIvfr771XiK22znBVd7i7dXv7uGoKLvWpcri19m/poh6JJmv+x9bsCSVAQlOCGR+g=,iv:AQ60dA38qSWALldh463n5aWFO8QeYBVuGMnHw+e+CBE=,tag:xZeq63wkL1q0lXIuhqnE7g==,type:str]
    version: 3.13.0
