---
keys:
  - &flux_key age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
  - &admin_sparks age1jayaggqedpe7djyjpk0a74xxc2vlqzumeah39f548rnkjse76syst7t4pl
  - &workstation_alpha age1p6y752pv3ze0a82lec5lyv5n20xex3ennpscgj8ueu7tecqpfd5s4wqe2j
  - &workstation_delta age17auaf780ad2m0jm5e348c8fpjeak3795jw8dgnmj6yk02whykdyq5eh9ps
  - &server_sierra age16ta5mdc8ywd0654q978a6t44ne02mmmg97xm9nnnpypk2e9ns9rs24lj6r
  - &server_romeo age1g7r4kxtrqwpxmv5uaj4pkfjx0pedw5yx9gmka4ppy34kqmc8rvuqp9ak6j
  - &server_whiskey age1jnc2r4een0mkr6pqkmd2xp50vd92fmgfukeffxlfgfy34w00l5vqzyz3kq
  - &server_tango age1e937w3zautvc5yev0zlwnlut35jdrfruz87ml68zd98s0tcghetq5v5u9n
  - &server_xray age18xs4rmgwdtpd0f7v89e4qgzu7r9ff0cg9g7duxxnm7gutlculdks52mqvx
  - &server_omega age1mz8x2r8xwhhljmnflvwvk68rge40zvjrtsdm29as4rahl3v7a4cq85m2jw
  - &server_lambda age106nfdadmxeg92rylfa5pxzhsv85whqgqkanjuwmpt8zydz880p0qnv2wym
  - &server_beta age1gxvmq7jj9f28pe6td68c2glmzxa9ja8g3pygd4xdm0zgnvdjlvgsgdawth
  - &server_kappa age1l9ujwxvu0ed9ed7aq6yqdqdj9wlky8vvfeqk4y2uu76fedkmq5dqhddh97

creation_rules:
  ## FLUX
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - *flux_key
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - *flux_key
  - path_regex: cluster/.*\.sops\.toml
    key_groups:
      - age:
          - *flux_key
  - path_regex: ansible/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - *flux_key
  - path_regex: terraform/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - *flux_key

  ## NixOS
  - path_regex: hosts/.*\.sops\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_sparks
          - *workstation_alpha
          - *workstation_delta
          - *server_sierra
          - *server_romeo
          - *server_whiskey
          - *server_tango
          - *server_xray
          - *server_omega
          - *server_lambda
          - *server_beta
          - *server_kappa
