---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-ai-backends-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/local-ai.sparks.codes/backends/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - beta

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-ai-backends-pvc
  namespace: ai
spec:
  volumeName: local-ai-backends-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
