---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volsync-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Ti
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/local/backups.sparks.codes/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - omega

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volsync-data-pvc
  namespace: volsync-system
spec:
  volumeName: local-volsync-data-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 6Ti
