---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-navidrome-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /mnt/local/navidrome.sparks.codes
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - tango

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-navidrome-pvc
  namespace: media
spec:
  volumeName: local-navidrome-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
