apiVersion: v1
data:
    username: ENC[AES256_GCM,data:H4vhqg==,iv:ZqB7QicUigE5NCZrgUL+qqt+JyIVqzKNSO/z8EvUCak=,tag:YH85JncIsEK6n+geD3UUWw==,type:str]
    password: ENC[AES256_GCM,data:CntdRLy4T8lslpVmm94ClBxY0ny5+KvpZO/osfpL9wFiiMbK,iv:JwAb/nGrXzWUERVEeQQJr5vt6hgUFiwC/a4hwaXAmpU=,tag:KafwmBx4EGV9LDG8fhOXiA==,type:str]
kind: Secret
metadata:
    name: litellm-db-secret
    namespace: ai
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU3lZeklRNS9MRzhQTmxY
            UHFCYmtubXlTQmtwbnd5eFd3UXZ5MlhSY0JvClBQOUF3UmNsSm9nL1dFR1FWZDNt
            cllKZnJQUXVDTWpCK2JObkhEbU0zbEkKLS0tIERCcHlHNHl0SHkrZTdoSjlBc2tK
            VzAwOVVIRnlrM2hROWxZZFV6U200YmsKgDdfCeu+SiGMegui+8Vo9sH7CLd8qNbI
            MSyCU31+fSZpcG3sg/yEYEx9JsbsIEaaGZbBD7RnH7mEfzMMkX+lTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T18:19:16Z"
    mac: ENC[AES256_GCM,data:Z/3zjg+vwytkj/FrqpOXjhg1L1TyYtqFhIgCbGYqkaN2dQE9kTLqgRF/KSoMc7oMnpwiN/aLEya4shCs8xscqKPP2HvSQP1IX4MrzBP6DSitpWbIXM5hxwghgMH4EtiCmXZfNQAtFVnwGQJUudI/AB5QaP/CryWGGKLQ8FajWvE=,iv:hePm6n9mV3o4p7CDUk/SFi7C0pNutYPxtycIpkWJ77A=,tag:lNGbSs5eDLhfeMd6HYY4pQ==,type:str]
    version: 3.13.1
