apiVersion: v1
data:
    username: ENC[AES256_GCM,data:H4vhqg==,iv:ZqB7QicUigE5NCZrgUL+qqt+JyIVqzKNSO/z8EvUCak=,tag:YH85JncIsEK6n+geD3UUWw==,type:str]
    password: ENC[AES256_GCM,data:MJbbQe9Xcaaf85GP8xZFHLG5wV8ZygUfcOyYSrJr0dM=,iv:WBzdRXMlWTAdjQI3NPAdGoV/a+tiuUIqsHrPX3mcuD8=,tag:mgX7x0yjhtagIgnyg2jQuA==,type:str]
kind: Secret
metadata:
    name: litellm-db-secret
    namespace: ai
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU3lZeklRNS9MRzhQTmxY
            UHFCYmtubXlTQmtwbnd5eFd3UXZ5MlhSY0JvClBQOUF3UmNsSm9nL1dFR1FWZDNt
            cllKZnJQUXVDTWpCK2JObkhEbU0zbEkKLS0tIERCcHlHNHl0SHkrZTdoSjlBc2tK
            VzAwOVVIRnlrM2hROWxZZFV6U200YmsKgDdfCeu+SiGMegui+8Vo9sH7CLd8qNbI
            MSyCU31+fSZpcG3sg/yEYEx9JsbsIEaaGZbBD7RnH7mEfzMMkX+lTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T18:41:13Z"
    mac: ENC[AES256_GCM,data:Iz1HXCYxFvZtzxSFR6KkRmgTbcjchVXb3tAXjGyjavlAhEjxWQUXhdc7JPA8oyAMeyFxuTXZOwv5l0PFJyoJHKs1TRvAd7lU4H8naPNICcvVdq2usr1vtWSg3kMAJgT9ftax1F+pzFw7I/sDyxHr6RbqOuauj8j1oLDwnzYn7n4=,iv:1232gGJhtUiW+qt1gFLh/CYw+I+uNmkJfjMY4g0Wh/k=,tag:z7BCyyALrSadFRgTI1SuIw==,type:str]
    version: 3.13.1
