apiVersion: v1
data:
    token: ENC[AES256_GCM,data:3ATbqiPFlV2V8DybE4XWDrNNS4Z9FySG8jvKLg==,iv:Urud2A1SFY2SvsS6Px37uWS/TF/ThE3Qk+/i0Mu85OQ=,tag:MvdDxTFBQNQeI8exmd3dTw==,type:str]
kind: Secret
metadata:
    name: litellm-master-secret
    namespace: ai
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU3lZeklRNS9MRzhQTmxY
            UHFCYmtubXlTQmtwbnd5eFd3UXZ5MlhSY0JvClBQOUF3UmNsSm9nL1dFR1FWZDNt
            cllKZnJQUXVDTWpCK2JObkhEbU0zbEkKLS0tIERCcHlHNHl0SHkrZTdoSjlBc2tK
            VzAwOVVIRnlrM2hROWxZZFV6U200YmsKgDdfCeu+SiGMegui+8Vo9sH7CLd8qNbI
            MSyCU31+fSZpcG3sg/yEYEx9JsbsIEaaGZbBD7RnH7mEfzMMkX+lTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T18:36:56Z"
    mac: ENC[AES256_GCM,data:fim3AwcmcfOadYP5VkjwxP/TsjfJbc7zsrRasKWBmKAU9ktqbmVHrvMgnjHBdQ4MKHzFQLFixIulsCgrQ5+ruRwOiEj3uWC1ea7M3ZBaLcxCpfLX/uJ71YWl6Mwe5VwSIgjHCx5Eq6mLvAQfD1WJ6W5xxgJ10HGiqgnAyf+bwgo=,iv:FqA01rR4cAmSS1jEVkizGGOT8Rc697ns4nHFzwdD+I0=,tag:qnJgBox4FYU32kXIo59M5w==,type:str]
    version: 3.13.1
