apiVersion: v1
stringData:
    PVC_DIR_NAME: ENC[AES256_GCM,data:xpKPTQy/HBo=,iv:gvenKe8EQU3x0Jf47vd+1gwu1I1FvGJ09O4ftapVt1k=,tag:oxe4FDCstp+YiS5YuQdQ3Q==,type:str]
    PVC_NAMESPACE: ENC[AES256_GCM,data:iphMO0dr207sl0Eicg==,iv:XK5HH6C2fj6E+oyV3+YDWp6hyNmOgHnaVV2UJc8MERU=,tag:ghGBRHNxcREYZmrkg/y1wQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:dFH5osOmg9kfhpqpNF5bnSJ2N+Pu5X/EBv133RkJK83kMXS0mbFIn3XAvFw1iU/0I6jktifpAYODw44OJCFpiSimEI0rYBz5MlzlUTjOWfU6lVlm2lg=,iv:6RBaxGNfge/TBI7NFHvpZ4BG9IDpjl1kLUODL9EduZ4=,tag:8JtPU8nB5vAi4oU7Y4qhig==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ZPK507D4N2Q55QZP1hW/pw==,iv:MxaXftTrFf3ATrFZHO0FDiA65GNvovIyrOUEVj4ziwY=,tag:6AHXe1FoxjPVq/P4r+CRmw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5KG3PtyjSYDzXc5jgV9Ccg==,iv:slFc6HfmYh8mCOsAE42uFHBmstUrltu1cn+b26K5nh0=,tag:QyKdNuQiWy+vxdIqHYHpaw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8kWm3xRGZ1j0gIbKF0nsyg==,iv:odTmV8W1XCRVx5C+XKlhBnvqCbnDQXTS72Ut9uE2MEo=,tag:Dy38QUymcJYrcD8BjI07Tw==,type:str]
kind: Secret
metadata:
    name: __NAME__-rustic-repository
    namespace: __NAMESPACE__
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MXN4SnU3ZTN2bEgwbm5L
            aE1qZExmMDJUeDJvalJZWE1mU1BPblBrN1NJCk1nV3U4TGp0d3M5d2YzeGdROUM2
            VUxremVVWllONVU2bzJodk50NklBUFEKLS0tIHZmZXppMXAvT3N6QlYzbDdsWnFs
            QUlwZndKNG1meTJZUHZBSTdHYVRBQ1EK6GO15QnFvo9Z68Ix6rExNfjjVFYoInWv
            pWxGJtH+nepwjzP5hMvhPxvQ8p4gVAjaRgkkucbQnlpSyYFd8tY91w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T18:21:10Z"
    mac: ENC[AES256_GCM,data:1izLxFquTSxI+yQ3bxADKuh4gRUWXduvJ0UXCqYqWZBcC6w1MetOjW6mSopbF7qrixWiwchXIdGB9/aO61Y9MLZqR7mp741POpPstQlF7iUilOnKfTo/7GdBLLoCwbKzkcLr/dEQMtFfSZn95K+ZXVGS4wufiaIgs2yz0vbUD6c=,iv:2waBefNDnFwJSi++54HFhrgLosrdQ3cz8zIXYIsSXZA=,tag:VXTUwkx/AdXNQUYCmIC+eg==,type:str]
    version: 3.13.3
