---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-ollama-openwebui
  namespace: ai
  annotations:
    tailscale.com/proxy-group: ollama-proxy
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - ollama-webui
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama-webui
                port:
                  number: 8080
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ollama-proxy
  namespace: ai
spec:
  type: ingress
  replicas: 1

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-ollama-api
  namespace: ai
  annotations:
    tailscale.com/proxy-group: ollama-proxy
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - ollama-api
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama
                port:
                  number: 8080
