apiVersion: v1
stringData:
    PVC_DIR_NAME: null
    PVC_NAMESPACE: null
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:bbS4OLEITG4meclUarskg01iuLGyBJA3cNIYQtKCZ6txoQJOW2oNjxqLR/sMEJoxM2jTpQu5SA==,iv:yy6vZNpz9iYbBjOmzyVlatOTc0dWoKifBK5WeLVqyEc=,tag:b4876sa1ARCl+1kgxtfSqA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:gFQ0CP5Rv8gzWsgBQzudLA==,iv:H74ZLdBsFsOrsdv4p3fSuISw5GX23A+d2QNWh7BDgF0=,tag:fAr18ORAPewnA+V4cZXZAQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6fHzEsiF1DavX0bOtTeCoA==,iv:EM4ihkqkV2C0Lkco01rDqJceJApukNR1lSLM3qHBcp8=,tag:l6jGTdWE9xslSm1uaMVnIA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Gvm3kveiEay7j8+Cqrnn9g==,iv:oQIjjbRcafhG8RJZOogGW5vgwsSyenjxWWkJ2QaQAng=,tag:bYdbdC14juxdsMgLTjE29g==,type:str]
kind: Secret
metadata:
    name: null-rustic-repository
    namespace: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeEZob2V4SERBeGNPa3o2
            Qnc2MFVjSHl5VkgvNiszcjBTYVErZFBEQng4Ck1CNkNWUnFFMGJxUi9VT1FOMGNB
            anNtT0VDeGJRcVhOSTF1QTg5aUdIUjgKLS0tIHZLL2JkNkEyNkFTNmFOMW9YQllS
            di9sbDVabkVKNE9mbjBEK3ZCOXEwQlEKnXc5zEcF+XAoMj1KTIKbT6OoybZn1MAD
            4x4Lo3Zi4nEpdromydOXhULXYOLZuCISIqV6TYanre0AqiyaNLd0vw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T19:11:58Z"
    mac: ENC[AES256_GCM,data:OCkJO2g7SitlxIGbD0qKpqIjwzzlgDTbTHYKujYW/8Pet2To+NVrgWNCVs4Yo48sLcuhOKxynXqPGVKe04Sne1xRep+ae5RcThw0HSY/XeEvkG6DNaIYHswD5nyq5En4bM4OPki3vGs8E8cw3aIuPjDocvBg6Uz+bTPXk4CMQco=,iv:aBnzwGvJ7xwlGkxX0cFddKtBinwVBJ31jSHw0NZYfIw=,tag:r8LBdyS4rN/m2C7iFk+ViA==,type:str]
    version: 3.13.3
