apiVersion: v1
stringData:
    PVC_DIR_NAME: ENC[AES256_GCM,data:fzNxrcg9jzHNO9Ee,iv:R2h2jgkKDqybz2ksAlQS2vE+HqThgy52f6zVpGYs0ls=,tag:Nu9YlR5Mn9f7nf6+F2lVHg==,type:str]
    PVC_NAMESPACE: ENC[AES256_GCM,data:7ws=,iv:k/ldyCYS+/gStpsHsgcJoNpvAi8ZfXNt7c2fo7RRZm0=,tag:1zQIYtItucJPtr2zY3iEDQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:z4lkIX02GtppOvkyHQw4I1xUQ4VOFNHr50x89O3/RlJD1Z5bzKSU3xRaILtQoxblq6bIctt+AjidXwIOWWBT,iv:tK5FnVhgKdLEXzt2JKXu299zqFcicxhDllQ419Nhofg=,tag:vuczGUv6jU3XevfvUVmVAQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:gFQ0CP5Rv8gzWsgBQzudLA==,iv:H74ZLdBsFsOrsdv4p3fSuISw5GX23A+d2QNWh7BDgF0=,tag:fAr18ORAPewnA+V4cZXZAQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6fHzEsiF1DavX0bOtTeCoA==,iv:EM4ihkqkV2C0Lkco01rDqJceJApukNR1lSLM3qHBcp8=,tag:l6jGTdWE9xslSm1uaMVnIA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Gvm3kveiEay7j8+Cqrnn9g==,iv:oQIjjbRcafhG8RJZOogGW5vgwsSyenjxWWkJ2QaQAng=,tag:bYdbdC14juxdsMgLTjE29g==,type:str]
kind: Secret
metadata:
    name: hermes-agent-rustic-repository
    namespace: ai
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeEZob2V4SERBeGNPa3o2
            Qnc2MFVjSHl5VkgvNiszcjBTYVErZFBEQng4Ck1CNkNWUnFFMGJxUi9VT1FOMGNB
            anNtT0VDeGJRcVhOSTF1QTg5aUdIUjgKLS0tIHZLL2JkNkEyNkFTNmFOMW9YQllS
            di9sbDVabkVKNE9mbjBEK3ZCOXEwQlEKnXc5zEcF+XAoMj1KTIKbT6OoybZn1MAD
            4x4Lo3Zi4nEpdromydOXhULXYOLZuCISIqV6TYanre0AqiyaNLd0vw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T19:18:03Z"
    mac: ENC[AES256_GCM,data:NVMDag5iidsGzANh0mBexrr9s96TgFEL1/XVyIm1oLaAU/4GxnoChp8nmamBjkaRXpbtYGZgWRUQ2YdrsMTh5Ddvlc4HoOX1AP94YkWhWlnlvSqw1IpTGmFwi/sjEjaUJrjvv0RfhuV0k7aKOPKmDlIR80WnyeQeLWYnj1mgclw=,iv:nF/dM6yPhfkBozdKvsAwWyBf8CVG7m9ZYcJ8SR74doE=,tag:chixhIRsxLWhG4s0BGConQ==,type:str]
    version: 3.13.3
