apiVersion: v1
stringData:
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:O1amcLm3,iv:Ra9bKxZhFr55zdvCGhLOf5HhvmNegSw4ZLfB21HZnw8=,tag:fDqeb9AwN3rdL7Lx4j8Q+A==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:Zwk6PnEPUraJZ+pJ5XCs,iv:vyQtuHv/P4zWnDhR8u4qr5Q5fIDZUkI64je9llBi6nk=,tag:rUDKuH38nbKIAwodSSy7uA==,type:str]
    SEARXNG_URL: ENC[AES256_GCM,data:mrYgcPHYr9ZqX2Y2eN7EGPxkrxIGuu4iMIv9,iv:X3YqQhpLxBdu71QHohnFQrstUErqeQiGQvFnenxjrQg=,tag:p0evfh73jlx2q5rsCEA+GA==,type:str]
kind: Secret
metadata:
    name: hermes-secret
    namespace: ai
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUzFKMEFGR3oyOGR0Ni9S
            d0hid2Y3aFNkRlhUa1g5L0RuS0FGdjhGZmx3Ck9MV3lNUG1pUzJoL3E4VGNWZCtq
            d2JJTWhYOHNTN2RqbXZScFBvRTNXRVkKLS0tIEluMXJmZ3h0cmVoWUMwT2Q3Ym8w
            NlFzQXdwbTVkdzlqYWV1MXBZSmRqdWcKKyueXsHUP32fhtXBGuFB/buLRCMPPYOO
            epnhbfo7p1DeE6Dnfli3SG5H2IK7heR6n8LJvaaQ+t8s1lXxVNs6cA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T20:12:24Z"
    mac: ENC[AES256_GCM,data:ATWam6pRWqKAsU5mGV6462co/QUOLEx1RKU7nw0FQWI8rN9nImjC8LfQ2BWgZNO25PCmS/ur8g27wc/N6cl9GB9JXdITsfTzfd8nBSshR2gpahh2FqwzdzofsHuu0jjlUZJGgJsYiyiNl2RUAHkkDiv3vEv9UhENni3JKgGZtlM=,iv:0A2LG196i2Wrxfm08Gy6mjKPnRn85p9tZav2j7tCoGU=,tag:gSF7Un19YIGD2SWqgJr5Xw==,type:str]
    version: 3.13.2
