---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur-charts
  namespace: flux-system
spec:
  interval: 15m
  url: oci://ghcr.io/home-operations/charts/kopiur
  ref:
    tag: 0.10.7
