---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm-oci-charts
  namespace: flux-system
spec:
  interval: 15m
  url: oci://docker.litellm.ai/berriai/litellm-helm
  ref:
    tag: 1.91.2
