---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-immich-pv
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /mnt/local/photos.sparks.codes
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - tango

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-immich-pvc
  namespace: media
spec:
  volumeName: local-immich-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 800Gi
